name: CI

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  style:
    secrets:
      token: ${{ secrets.PAT }}
    uses: ComPWA/actions/.github/workflows/pre-commit.yml@v1
